name: debsahu-hugo
static_sites:
- build_command: rm -r ./public; hugo --destination ./public
  environment_slug: hugo
  envs:
  - key: HUGO_VERSION
    scope: BUILD_TIME
    value: 0.146.7
  git:
    branch: main
    repo_clone_url: https://github.com/debsahu/debsahu-hugo.git
  name: debsahu-hugo
  routes:
  - path: /
  source_dir: youtube