name: debsahu-hugo
static_sites:
- build_command: rm -r ./public; hugo --source youtube --destination ./public
  environment_slug: hugo
  github:
    branch: main
    deploy_on_push: true
    repo: debsahu/debsahu-hugo
  name: debsahu-hugo