name: Hugo

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [0.146.7]
        image: [ext-alpine]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set permissions
      run: |
        mkdir -p /tmp/hugo-cache
        chmod -R 777 /tmp/hugo-cache
        chmod -R 777 ./youtube

    - name: hugo
      uses: floryn90/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
        source: youtube
        env: production
        cache-dir: /tmp/hugo-cache
