name: Hugo

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [0.123.4]
        image: [ext-alpine]
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hugo
      uses: floryn90/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
        source: youtube
        env: production
